[2018-07-23 13:20:48.144] [INFO] console - 返回结果===
[2018-07-23 13:20:48.744] [ERROR] console - { Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'haitaowa_test'@'220.168.52.211' (using password: YES)
    at Handshake.Sequence._packetToError (E:\vnode-blog\node_modules\mysql\lib\protocol\sequences\Sequence.js:52:14)
    at Handshake.ErrorPacket (E:\vnode-blog\node_modules\mysql\lib\protocol\sequences\Handshake.js:130:18)
    at Protocol._parsePacket (E:\vnode-blog\node_modules\mysql\lib\protocol\Protocol.js:279:23)
    at Parser.write (E:\vnode-blog\node_modules\mysql\lib\protocol\Parser.js:76:12)
    at Protocol.write (E:\vnode-blog\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (E:\vnode-blog\node_modules\mysql\lib\Connection.js:103:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    --------------------
    at Protocol._enqueue (E:\vnode-blog\node_modules\mysql\lib\protocol\Protocol.js:145:48)
    at Protocol.handshake (E:\vnode-blog\node_modules\mysql\lib\protocol\Protocol.js:52:23)
    at Connection.connect (E:\vnode-blog\node_modules\mysql\lib\Connection.js:130:18)
    at Connection._implyConnect (E:\vnode-blog\node_modules\mysql\lib\Connection.js:461:10)
    at Connection.query (E:\vnode-blog\node_modules\mysql\lib\Connection.js:206:8)
    at E:\vnode-blog\api\router\index.js:113:9
    at Layer.handle [as handle_request] (E:\vnode-blog\node_modules\express\lib\router\layer.js:95:5)
    at next (E:\vnode-blog\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (E:\vnode-blog\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (E:\vnode-blog\node_modules\express\lib\router\layer.js:95:5)
  code: 'ER_ACCESS_DENIED_ERROR',
  errno: 1045,
  sqlMessage: 'Access denied for user \'haitaowa_test\'@\'220.168.52.211\' (using password: YES)',
  sqlState: '28000',
  fatal: true }
Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'haitaowa_test'@'220.168.52.211' (using password: YES)
    at Handshake.Sequence._packetToError (E:\vnode-blog\node_modules\mysql\lib\protocol\sequences\Sequence.js:52:14)
    at Handshake.ErrorPacket (E:\vnode-blog\node_modules\mysql\lib\protocol\sequences\Handshake.js:130:18)
    at Protocol._parsePacket (E:\vnode-blog\node_modules\mysql\lib\protocol\Protocol.js:279:23)
    at Parser.write (E:\vnode-blog\node_modules\mysql\lib\protocol\Parser.js:76:12)
    at Protocol.write (E:\vnode-blog\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (E:\vnode-blog\node_modules\mysql\lib\Connection.js:103:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    --------------------
    at Protocol._enqueue (E:\vnode-blog\node_modules\mysql\lib\protocol\Protocol.js:145:48)
    at Protocol.handshake (E:\vnode-blog\node_modules\mysql\lib\protocol\Protocol.js:52:23)
    at Connection.connect (E:\vnode-blog\node_modules\mysql\lib\Connection.js:130:18)
    at Connection._implyConnect (E:\vnode-blog\node_modules\mysql\lib\Connection.js:461:10)
    at Connection.query (E:\vnode-blog\node_modules\mysql\lib\Connection.js:206:8)
    at E:\vnode-blog\api\router\index.js:113:9
    at Layer.handle [as handle_request] (E:\vnode-blog\node_modules\express\lib\router\layer.js:95:5)
    at next (E:\vnode-blog\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (E:\vnode-blog\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (E:\vnode-blog\node_modules\express\lib\router\layer.js:95:5)
[2018-07-23 13:20:48.863] [INFO] console - ::1 - - "POST /api/login HTTP/1.1" 200 35 "http://localhost:8088/login" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36"
